name: Create Custom Branch on Issue Open

on:
  issues:
    types: [opened]

jobs:
  create-custom-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Debug issue body
        run: |
          echo "### ISSUE BODY START ###"
          cat $GITHUB_EVENT_PATH | jq -r '.issue.body'
          echo "### ISSUE BODY END ###"

      - name: Extract branch name
        id: branch-input
        run: |
          # ì´ìŠˆ ë³¸ë¬¸ì—ì„œ "ðŸŒ³ ë¸Œëžœì¹˜ëª… (Branch)" ë‹¤ìŒ ì¤„ì„ ê°€ì ¸ì˜¤ê¸°
          BRANCH_NAME=$(jq -r '.issue.body' $GITHUB_EVENT_PATH | awk -v RS="\n" '/ðŸŒ³ ë¸Œëžœì¹˜ëª… \(Branch\)/ {getline; print}')

          # ë¸Œëžœì¹˜ëª…ì´ ë¹„ì–´ìžˆìœ¼ë©´ ì˜¤ë¥˜ ì¶œë ¥ í›„ ì¢…ë£Œ
          if [[ -z "$BRANCH_NAME" ]]; then
            echo "ë¸Œëžœì¹˜ëª…ì„ ì°¾ì„ ìˆ˜ ì—†ìŠµë‹ˆë‹¤."
            exit 1
          fi

          echo "branch=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create branch
        run: |
          git checkout -b "${{ steps.branch-input.outputs.branch }}"
          git push origin "${{ steps.branch-input.outputs.branch }}"
        env:
          GH_TOKEN: ${{ secrets.TOKEN_GITHUB }}
