name: Create Custom Branch on Issue Open

on:
  issues:
    types: [opened]

jobs:
  create-custom-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Debug issue body
        run: cat $GITHUB_EVENT_PATH | jq -r '.issue.body'

      - name: Extract branch name
        id: branch-input
        run: |
          BRANCH_NAME=$(jq -r '.issue.body' $GITHUB_EVENT_PATH | sed -n '/ðŸŒ³ ë¸Œëžœì¹˜ëª… (Branch)/{n;p}')

          if [[ -z "$BRANCH_NAME" ]]; then
            echo "ë¸Œëžœì¹˜ëª…ì„ ì°¾ì„ ìˆ˜ ì—†ìŠµë‹ˆë‹¤."
            exit 1
          fi

          echo "branch=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create branch
        run: |
          git checkout -b "${{ steps.branch-input.outputs.branch }}"
          git push origin "${{ steps.branch-input.outputs.branch }}"
        env:
          GH_TOKEN: ${{ secrets.TOKEN_GITHUB }}
