name: Create Custom Branch on Issue Open

on:
  issues:
    types: [opened]

jobs:
  create-custom-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        id: branch-input
        run: |
          # ì´ìŠˆ ë³¸ë¬¸ì—ì„œ "ğŸŒ³ ë¸Œëœì¹˜ëª… (Branch)" ë‹¤ìŒì— ì˜¤ëŠ” ê°’ì„ ì°¾ê¸°
          BRANCH_NAME=$(jq -r '.issue.body' $GITHUB_EVENT_PATH | grep -oP '(?<=ğŸŒ³ ë¸Œëœì¹˜ëª… \(Branch\)\n).+' | head -n 1)

          if [[ -z "$BRANCH_NAME" ]]; then
            echo "ë¸Œëœì¹˜ëª…ì„ ì°¾ì„ ìˆ˜ ì—†ìŠµë‹ˆë‹¤."
            exit 1
          fi

          echo "branch=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create branch
        run: |
          git checkout -b "${{ steps.branch-input.outputs.branch }}"
          git push origin "${{ steps.branch-input.outputs.branch }}"
        env:
          GH_TOKEN: ${{ secrets.TOKEN_GITHUB }}
